### ISSUE TITLE
RuntimeError: Invalid function argument. Expected parameter `tensor` to be of type torch.Tensor.

### ISSUE THREAD

**Issue by htfhxx** [SCHENLIU/longformer-chinese#15]
使用的多卡，请问有出现同样问题的吗，有没有啥解决思路？
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/34822492/164030380-0a8b96ce-6e6f-486b-9cfd-86d3ba5a5199.png">

**Comment by htfhxx** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/34822492/164029870-3c383a34-35aa-46b5-8a5a-4003fdff525d.png">

**Comment by melissamao** [comment]
hello~我想问一下我也遇到了相同的问题，想问一下您是怎么解决的
